version: '3.8'
services:
  bd:
    image: mysql:8
    environment:
     - MYSQL_ROOT_PASSWORD=insitelSAS90
     - MYSQL_DATABASE=inventario
    ports:
      - 3307:3306

  app:
    build: .
    depends_on:
      - bd
    links:
      - bd
    ports:
      - 4001:4001
    volumes:
      - .:/usr/src/app
